CREATE TABLE IF NOT EXISTS `itmo_db`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8